<?php
	$pay_basic=array(
			"pay_name"=>"微信支付",
			"type"=>"online",
			"pay_dir"=>"wxpay",
			"pay_dev"=>"kekezu",
			"pay_desc"=>"微信扫码支付",
			"img"=>"wxpay.gif",
			'rate_img'=>'rate_img',
			"initparam"=>"appid:公众帐号APPID;appsecert:公众帐号appsecert;mchid:商户号;key:商户支付密钥"
	);
?>